In [2]:
import numpy as np
a=np.array ([10,20,30,40])
print("one dimenstional array:",a)


one dimenstional array: [10 20 30 40]


In [3]:
import numpy as np
b=np.array([[10,20,30,40],[50,60,70,80]])
print("Two dimenstional array:",b)

Two dimenstional array: [[10 20 30 40]
 [50 60 70 80]]


In [4]:
import numpy as np
c=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Three dimenstional array:",c)

Three dimenstional array: [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [5]:
import numpy as np
d=np.zeros((3,5))
print("\n array with all zeors:\n",d)



 array with all zeors:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
import numpy as np
e=np.random.random((5,6))
print("\n random value:\n",e)


 random value:
 [[0.07002638 0.28955529 0.54648969 0.04258103 0.2559223  0.07090139]
 [0.29462541 0.79481945 0.0124122  0.5756333  0.49086136 0.57901494]
 [0.94630568 0.7592566  0.51460589 0.01381482 0.44899036 0.17847554]
 [0.15824512 0.34250425 0.21085928 0.77286065 0.83802365 0.92856161]
 [0.76026405 0.38150352 0.86836327 0.72013047 0.59488144 0.05894668]]


In [7]:
import numpy as np
f=np.arange(6,12,4)
print("\n sequence array:\n",f)


 sequence array:
 [ 6 10]


In [8]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a.reshape(4,3)
print("\n old array:\n",a)
print("\n reshaped array:\n",b)


 old array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 reshaped array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
m=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
flat=m.flatten()
print("\n original array:\n",m)
print("flattened array:\n",flat)


 original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
flattened array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [15]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("\n no of dimemnstional array:\n",a.ndim)


 no of dimemnstional array:
 2


In [21]:
b=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("\n no of dimenstioanl array:\n",b.ndim)


 no of dimenstioanl array:
 3


In [24]:
b=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("\n no of dimenstional array:\n",b.ndim)
print("\n shape of array:",b.shape)
print("\n elemental array:\n",b.dtype)


 no of dimenstional array:
 3

 shape of array: (2, 2, 3)

 elemental array:
 int64


In [25]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("\n size of array\n",a.size)


 size of array
 12


In [ ]:
import numoy as np
a=[10,20,30]
a=np.array(a)
