In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice =arr[2:6]
print (slice)

[3 4 5 6]


In [7]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice=arr[::2]
print(slice)

[1 3 5 7 9]


In [8]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice=arr[::3]
print(slice)

[1 4 7]


In [9]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice=arr[::4]
print(slice)

[1 5 9]


In [16]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
slice=a[::-1]
print("Reversed array=",slice)


Reversed array= [9 8 7 6 5 4 3 2 1]


In [18]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray=a[0:2,1:3]
print("sliced multidimentional array=\n",subarray)

sliced multidimentional array=
 [[2 3]
 [5 6]]


In [20]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray=a[:2,:1]
print(subarray)

[[1]
 [4]]


In [30]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
row1 = a[0,:]
print("Extracted first row = ",row1)

Extracted first row =  [1 2 3]


In [32]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
row1=a[0:2:1]
print("rows=\n",row1)

rows=
 [[1 2 3]
 [4 5 6]]


In [40]:
import numpy as np
import array
arr=[10,20,30]
print(a[0])

1


In [4]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
#horizontal join
result=np.hstack((a,b))
print(result)


[[1 2 5 6]
 [3 4 7 8]]


In [6]:
import numpy as np
a=np.array([[1,2,],[3,4]])
b=np.array([[5,6],[7,8]])
#vertical join
result=np.vstack((a,b))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [7]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
#depth join
result=np.dstack((a,b))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [9]:
import numpy as np
a=np.array([1,2,3,4,5,6])
result=np.split(a,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [12]:
import numpy as np
a=np.array([1,2,3,4,5])
result=np.array_split(a,3)
print(result)

[array([1, 2]), array([3, 4]), array([5])]
